<?php
// Auto-derived from Project_Details_Merged.xlsx — do not hand-edit; regenerate from source workbook.
// NOTE: 'lat' and 'lng' were added manually (not part of the original Excel export) to power
// the Interactive Gurugram Map on project.php. These are best-estimate real-world sector
// coordinates and can be corrected/replaced at any time without touching any other field.
// NOTE: 'image' was added manually to map each project to its file inside
// assets/img/projects/. If a project's image file does not exist yet, 'image'
// is set to 'default-project.webp' as a safe fallback.
return [
    [
        'title' => 'Smart World One DXP',
        'image' => 'smart-world-one-dxp.webp',
        'sector_raw' => 'Sec-113',
        'location' => 'Dwarka Exp.',
        'lat' => 28.4595,
        'lng' => 76.9998,
        'land' => '16 Acres',
        'land_num' => 16.0,
        'towers' => '16',
        'height' => 'G+29',
        'clubhouse' => '1 Lac Sqft',
        'possession_raw' => '2029-06-01 00:00:00',
        'payment_plan' => '25:75',
        'usp_raw' => '1. Bang on Dwarka Expressway
2. Fully Loaded Apartment - VRV AC, Modular Kitchen
3. 0 Km Delhi
4. Mivan Construction',
        'min_price' => 5.0,
        'max_price' => 5.85,
        'typologies' => ['3BHK+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+S','typology'=>'2580-2600 Sq. ft.','price'=>'5 Cr*'], ['size'=>'4BHK+S','typology'=>'3000-3200 Sq. ft.','price'=>'5.85 Cr*']],
    ],
    [
        'title' => 'Emaar Urban Ascent',
        'image' => 'emaar-urban-ascent.webp',
        'sector_raw' => 'Sec-112',
        'location' => 'Dwarka Exp.',
        'lat' => 28.4645,
        'lng' => 77.0045,
        'land' => '9 Acres',
        'land_num' => 9.0,
        'towers' => '6',
        'height' => 'G+42',
        'clubhouse' => '60k Sqft',
        'possession_raw' => '2030',
        'payment_plan' => '30:40:30',
        'usp_raw' => '1. 75% Open and Green
2. Fully Loaded
3. Mivan Construction
4. Near to Delhi',
        'min_price' => 3.75,
        'max_price' => 5.28,
        'typologies' => ['3BHK+S+3T', '4BHK+S'],
        'configs' => [['size'=>'3BHK+S+3T','typology'=>'2165 Sq. ft.','price'=>'3.75 Cr*'], ['size'=>'4BHK+S','typology'=>'2816 Sq. ft.','price'=>'4.70 Cr*'], ['size'=>'4BHK+S','typology'=>'3151 Sq. ft.','price'=>'5.28 Cr*']],
    ],
    [
        'title' => 'Adani The Mark',
        'image' => 'adani-the-mark.webp',
        'sector_raw' => 'Sec-102A',
        'location' => 'Dwarka Exp.',
        'lat' => 28.4780,
        'lng' => 77.0250,
        'land' => '5 Acres',
        'land_num' => 5.0,
        'towers' => '2',
        'height' => 'G+46',
        'clubhouse' => '35k Sqft',
        'possession_raw' => '2031',
        'payment_plan' => 'CLP',
        'usp_raw' => '1. Prime Location - Bang on 75 mt. Road
2. Iconic Tower
3. 70% open and green area
4. Fully Loaded Apartment',
        'min_price' => 3.99,
        'max_price' => 5.29,
        'typologies' => ['3BHK+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+S','typology'=>'2350 Sq. ft.','price'=>'3.99 Cr*'], ['size'=>'4BHK+S','typology'=>'3250 Sq. ft.','price'=>'5.29 Cr*']],
    ],
    [
        'title' => 'Signature Global Sarvam',
        'image' => 'signature-global-sarvam.webp',
        'sector_raw' => 'Sec-37D',
        'location' => 'Dwarka Exp.',
        'lat' => 28.4550,
        'lng' => 76.9850,
        'land' => '13.5 Acres',
        'land_num' => 13.5,
        'towers' => '14',
        'height' => 'G+35/40',
        'clubhouse' => '1 Lac Sqft',
        'possession_raw' => '2032',
        'payment_plan' => 'CLP',
        'usp_raw' => '1. Designed as an integrated township
2. Emphasis on open green spaces
3. Children’s play area and sports facilities ',
        'min_price' => 2.89,
        'max_price' => 3.94,
        'typologies' => ['3BHK+2T', '3BHK+3T', '3BHK+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+2T','typology'=>'1815-1840 Sq. ft.','price'=>'2.89 Cr*'], ['size'=>'3BHK+3T','typology'=>'2050 Sq. ft.','price'=>'3.26 Cr*'], ['size'=>'3BHK+S','typology'=>'2260-2340 Sq. ft.','price'=>'3.60 Cr*'], ['size'=>'4BHK+S','typology'=>'2495 Sq. ft.','price'=>'3.94 Cr*']],
    ],
    [
        'title' => 'Godrej Vriksha',
        'image' => 'godrej-vriksha.webp',
        'sector_raw' => 'Sec-103',
        'location' => 'Dwarka Exp.',
        'lat' => 28.4720,
        'lng' => 77.0180,
        'land' => '14.5 Acres',
        'land_num' => 14.5,
        'towers' => '6',
        'height' => 'G+26',
        'clubhouse' => '90k Sqft',
        'possession_raw' => '2030',
        'payment_plan' => '06:40:30',
        'usp_raw' => '1. Low Density
2.  85% Open and green 
3. Resort-Style Living',
        'min_price' => 3.7,
        'max_price' => 7.0,
        'typologies' => ['3BHK+3T', '3BHK+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+3T','typology'=>'1948 Sq. ft.','price'=>'3.70 Cr*'], ['size'=>'3BHK+S','typology'=>'2243 Sq. ft.','price'=>'4.26 Cr*'], ['size'=>'3BHK+S','typology'=>'2430 Sq. ft.','price'=>'4.60 Cr*'], ['size'=>'4BHK+S','typology'=>'2658 Sq. ft.','price'=>'5 Cr*'], ['size'=>'4BHK+S','typology'=>'3700 Sq. ft.','price'=>'7 Cr*']],
    ],
    [
        'title' => 'Smart World Edition',
        'image' => 'smart-world-edition.webp',
        'sector_raw' => 'Sec-66',
        'location' => 'Golf-Course Ext. Rd.',
        'lat' => 28.4090,
        'lng' => 77.0680,
        'land' => '11 Acres',
        'land_num' => 11.0,
        'towers' => '6',
        'height' => 'G+42',
        'clubhouse' => '1 Lac Sqft',
        'possession_raw' => '2030',
        'payment_plan' => '25:75',
        'usp_raw' => '1. Architectural Marvel
2. Private Decks: Wrap-around balconies with panoramic views of the skyline.
3. Ahluwalia construction Partner
4. 12 feet Ceiling height',
        'min_price' => 6.5,
        'max_price' => 7.7,
        'typologies' => ['3BHK+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+S','typology'=>'3035 Sq. ft.','price'=>'6.50 Cr*'], ['size'=>'4BHK+S','typology'=>'3660 Sq. ft.','price'=>'7.70 Cr*']],
    ],
    [
        'title' => 'Smart World Sky Arc',
        'image' => 'smart-world-sky-arc.webp',
        'sector_raw' => 'Sec-69',
        'location' => 'Golf-Course Ext. Rd.',
        'lat' => 28.3980,
        'lng' => 77.0730,
        'land' => '12 Acres',
        'land_num' => 12.0,
        'towers' => '6',
        'height' => 'G+43',
        'clubhouse' => '1 Lac Sqft',
        'possession_raw' => '2031',
        'payment_plan' => '25:75',
        'usp_raw' => '1. Architectural design inspired by Marina Bay Sands, Singapore.
2. Signature 2.5-acre Sky Club on the top floor
3. Fully Loaded Apartments',
        'min_price' => 4.99,
        'max_price' => 7.0,
        'typologies' => ['3BHK+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+S','typology'=>'2355 Sq. ft.','price'=>'4.99 Cr*'], ['size'=>'3BHK+S','typology'=>'2690 Sq. ft.','price'=>'5.78 Cr*'], ['size'=>'4BHK+S','typology'=>'3270 Sq. ft.','price'=>'7 Cr*']],
    ],
    [
        'title' => 'Sobha Crescent',
        'image' => 'sobha-crescent.webp',
        'sector_raw' => 'Sec-63A',
        'location' => 'Golf Course Ext. Rd.',
        'lat' => 28.4150,
        'lng' => 77.0600,
        'land' => '11.2 Acres',
        'land_num' => 11.2,
        'towers' => '4',
        'height' => 'G+40/42',
        'clubhouse' => '1 Lac Sqft',
        'possession_raw' => '2032',
        'payment_plan' => 'CLP',
        'usp_raw' => '1. Elite Low Density
2. 80% open and green area
3. In house Construction',
        'min_price' => 5.49,
        'max_price' => 7.11,
        'typologies' => ['3BHK+3T', '3BHK+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+3T','typology'=>'2287-2333 Sq. ft.','price'=>'5.49 Cr*'], ['size'=>'3BHK+S','typology'=>'2670 Sq. ft.','price'=>'6.40 Cr*'], ['size'=>'4BHK+S','typology'=>'2966 Sq. ft.','price'=>'7.11 Cr*']],
    ],
    [
        'title' => 'Adani Samsara Vilasa',
        'image' => 'adani-samsara-vilasa.webp',
        'sector_raw' => 'Sec-63A',
        'location' => 'Golf Course Ext. Rd.',
        'lat' => 28.4157,
        'lng' => 77.0611,
        'land' => '65 Acres Integrated Township',
        'land_num' => 65.0,
        'towers' => null,
        'height' => 'Independent Floor',
        'clubhouse' => '1 Lac Sqft',
        'possession_raw' => '2029 Dec.',
        'payment_plan' => '30:40:30',
        'usp_raw' => '1. Low Density
2. Developed Location
3. Spacious Apartment
',
        'min_price' => 5.87,
        'max_price' => 5.87,
        'typologies' => ['Plot Size (351 Sq. Yard)', '4BHK+S'],
        'configs' => [['size'=>'Plot Size (351 Sq. Yard)','typology'=>null,'price'=>null], ['size'=>'4BHK+S','typology'=>'3250 Sq. ft.','price'=>'5.87 Cr*']],
    ],
    [
        'title' => 'Ashiana Aaroham',
        'image' => 'ashiana-aaroham.webp',
        'sector_raw' => 'Sec-80',
        'location' => 'New Gurgaon',
        'lat' => 28.3550,
        'lng' => 76.9700,
        'land' => '11 Acres',
        'land_num' => 11.0,
        'towers' => '6',
        'height' => 'G+23',
        'clubhouse' => '40k Sqft',
        'possession_raw' => '2031',
        'payment_plan' => '20:40:40',
        'usp_raw' => '1. Curated Kid Centric home.
2. Low density property.
3. 85% open and green area.',
        'min_price' => 2.99,
        'max_price' => 4.1,
        'typologies' => ['3BHK', '4BHK'],
        'configs' => [['size'=>'3BHK','typology'=>'1800 Sq. ft.','price'=>'2.99 Cr*'], ['size'=>'3BHK','typology'=>'2100 Sq. ft.','price'=>'3.38 Cr*'], ['size'=>'4BHK','typology'=>'2600 Sq. ft.','price'=>'4.10 Cr*']],
    ],
    [
        'title' => 'Emaar Serenity Hills',
        'image' => 'emaar-serenity-hills.webp',
        'sector_raw' => 'Sec-86',
        'location' => 'New Gurgaon',
        'lat' => 28.3650,
        'lng' => 76.9600,
        'land' => '26 Acres',
        'land_num' => 26.0,
        'towers' => '13',
        'height' => 'G+35/39',
        'clubhouse' => '2 Lac Sqft',
        'possession_raw' => '2032',
        'payment_plan' => '06:40:30',
        'usp_raw' => '1. 20 Acre Open and green area
2. 8 Acre Central Green
3. Mivan Construction
4. 90 % open and green area.',
        'min_price' => 2.98,
        'max_price' => 5.28,
        'typologies' => ['3BHK+2T', '3BHK+3T+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+2T','typology'=>'1750 Sq. ft.','price'=>'2.98 Cr*'], ['size'=>'3BHK+3T+S','typology'=>'2280 Sq. ft.','price'=>'3.87 Cr*'], ['size'=>'4BHK+S','typology'=>'2970 Sq. ft.','price'=>'5.28 Cr*']],
    ],
    [
        'title' => 'Signature Global Cloverdale',
        'image' => 'signature-global-cloverdale.webp',
        'sector_raw' => 'Sec-71',
        'location' => 'SPR Rd.',
        'lat' => 28.4020,
        'lng' => 77.0850,
        'land' => '12 Acres',
        'land_num' => 12.0,
        'towers' => '6',
        'height' => 'G+35',
        'clubhouse' => '65k Sqft',
        'possession_raw' => '2030',
        'payment_plan' => 'CLP',
        'usp_raw' => '1. Expansive green zones 
2. Modern architecture & well-planned layouts
3. IGBC-certified sustainable development',
        'min_price' => 3.89,
        'max_price' => 6.61,
        'typologies' => ['3BHK', '3BHK+S', '4BHK'],
        'configs' => [['size'=>'3BHK','typology'=>'2090 Sq. ft.','price'=>'3.89 Cr*'], ['size'=>'3BHK+S','typology'=>'2280 Sq. ft.','price'=>'4.21 Cr*'], ['size'=>'4BHK','typology'=>'2780-3480 Sq. ft.','price'=>'6.61 Cr*']],
    ],
    [
        'title' => 'Titanium SPR',
        'image' => 'titanium-spr.webp',
        'sector_raw' => 'Sec-71',
        'location' => 'SPR Rd.',
        'lat' => 28.4026,
        'lng' => 77.0858,
        'land' => '14 Acres',
        'land_num' => 14.0,
        'towers' => '7',
        'height' => 'G+40',
        'clubhouse' => '65k Sqft',
        'possession_raw' => '2030',
        'payment_plan' => 'CLP',
        'usp_raw' => '1. Expansive green zones 
2. Modern architecture & well-planned layouts
3. IGBC-certified sustainable development
4. Two apartments per floor',
        'min_price' => 5.15,
        'max_price' => 7.18,
        'typologies' => ['3BHK+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+S','typology'=>'2780 Sq. ft.','price'=>'5.15 Cr*'], ['size'=>'4BHK+S','typology'=>'3780 Sq. ft.','price'=>'7.18 Cr*']],
    ],
    [
        'title' => 'Smart World the Nature Court',
        'image' => 'smart-world-the-nature-court.webp',
        'sector_raw' => 'Manesar',
        'location' => 'M-9, M-10, M-11 Manesar, Gurgaon',
        'lat' => 28.3550,
        'lng' => 76.9350,
        'land' => '22 Acres',
        'land_num' => 22.0,
        'towers' => '10 Twin Tower',
        'height' => 'G+22',
        'clubhouse' => '80k Sqft',
        'possession_raw' => '2031',
        'payment_plan' => 'CLP/FLXI/PLP',
        'usp_raw' => '1. Fully Air Conditionar Apartment
2. Modular Kitchen with Chimeny and Hub
3. Forest Theme
4. 140 Acres Integrated Township ',
        'min_price' => 1.54,
        'max_price' => 1.56,
        'typologies' => ['2.5 BHK'],
        'configs' => [['size'=>'2.5 BHK','typology'=>'1339 Sq. ft.','price'=>'1.54 Cr*'], ['size'=>'2.5 BHK','typology'=>'1360 Sq. ft.','price'=>'1.56 Cr*']],
    ],
    [
        'title' => 'Experion The Trillion',
        'image' => 'experion-the-trillion.webp',
        'sector_raw' => 'Sec-48',
        'location' => 'Sohna Rd.',
        'lat' => 28.4180,
        'lng' => 77.0450,
        'land' => '5 Acres',
        'land_num' => 5.0,
        'towers' => '3',
        'height' => 'G+45',
        'clubhouse' => '60k Sqft',
        'possession_raw' => '2030',
        'payment_plan' => '20:80',
        'usp_raw' => '1.Construction Partner: TATA Projects
2. Holistic living
3. Expansive lawns, shaded pathways  ',
        'min_price' => 6.25,
        'max_price' => 8.15,
        'typologies' => ['3BHK+S', '4BHK+S'],
        'configs' => [['size'=>'3BHK+S','typology'=>'2600-2700 Sq. ft.','price'=>'6.25 Cr*'], ['size'=>'4BHK+S','typology'=>'3500-3600 Sq. ft.','price'=>'8.15 Cr*']],
    ],
    [
        'title' => 'Smart World Hero Palatial',
        'image' => 'smart-world-hero-palatial.webp',
        'sector_raw' => 'Sec-104',
        'location' => 'Dwarka Exp.',
        'lat' => 28.4800,
        'lng' => 77.0300,
        'land' => '11 Acres',
        'land_num' => 11.0,
        'towers' => '5',
        'height' => 'G+43',
        'clubhouse' => '1 Lac Sqft',
        'possession_raw' => '2031',
        'payment_plan' => '30:40:30',
        'usp_raw' => '1. Full Loaded - Fall ceiling, washroom fitting, VRV AC, wardrobe, etc.
2. 30:70 (Special Payment Plan)
3. Bang on Dwarka Exp.
4. Japenese theme',
        'min_price' => 5.25,
        'max_price' => 6.4,
        'typologies' => ['3BHK', '4BHK+S'],
        'configs' => [['size'=>'3BHK','typology'=>'2833 Sq. ft.','price'=>'5.25 Cr*'], ['size'=>'4BHK+S','typology'=>'3457 Sq. ft.','price'=>'6.40 Cr*']],
    ],
];